project:
  type: default
  output-dir: _output
  preview: 
    port: 4444

  render: 
    - "index.qmd"

language: 
  title-block-published: Latest version
  related-formats-title: Other formats
  other-links-title: Other links

format:
  wordcount-html: 
    wordcount-banner: false

    toc: true
    shift-heading-level-by: 1
    theme: 
      - zephyr
      - brand
    # MoMAColors::moma.colors("ustwo")[2]
    title-block-banner: "#f06a63"

    template-partials: 
      - "html/title-metadata.html"

    format-links:
      - html
      - format: typst
        text: PDF version
        icon: file-pdf
      # - format: docx
      #   text: Word version
      #   icon: file-word

    other-links:
      - text: GitHub repository
        href: https://github.com/andrewheiss/pinky-lychee/
        icon: github
      # - text: SocArXiv preprint
      #   href: https://doi.org/10.31235/osf.io/wvecz_v3
      #   icon: link-45deg

    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300
  
  typst:
    output-file: heiss_ai-for-me-not-yet-for-thee.pdf
    pdf-standard: ua-1
    margin:
      top: 120pt    # 10p0
      bottom: 120pt #10p0
      left: 132pt   # 11p0
      right: 132pt  # 11p0

    mainfont: "Linux Libertine O"
    fontsize: 10.5pt

    citeproc: true
    link-citations: true
    linkcolor: "#D64038"

    include-in-header:
      text: |
        #set par(
          first-line-indent: 1em,
          spacing: 0.65em
        )

        #show <refs>: it => {
          set par(hanging-indent: 1em)
          set text(size: 9.5pt)
          it
        }
  
  # Manuscript-y Word
  docx:
    output-file: heiss_ai-for-me-not-yet-for-thee.docx
    reference-doc: pandoc/reference-styles.docx

    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300
